### ISSUE TITLE
Problem with run main.py - no module nuimo

### ISSUE THREAD

**Issue by Hanimaniac** [pfink/nuimo-openhab-python#16]
Hello Everyone,
I'm new in the openHAB world and try to get my nuimo control to control my sonos system. 
I followed the Instructions here, but when i start the python3 main.py command, it follows: 

@openHAB-pi:/etc/openhab2/nuimo-openhab-python $ python3 main.py
Traceback (most recent call last):
  File "/etc/openhab2/nuimo-openhab-python/main.py", line 6, in <module>
    from nuimo_menue.listener import *
  File "/etc/openhab2/nuimo-openhab-python/nuimo_menue/listener.py", line 4, in <module>
    import nuimo
ModuleNotFoundError: No module named 'nuimo'

I can't find the 'nuimo'. 

When I start with - systemctl start nuimo-openhab - and watch with - systemctl status - no nuimo-openhab is shown:

@openHAB-pi:/etc/openhab2/nuimo-openhab-python $ sudo systemctl status 
● openHAB-pi
    State: degraded
    Units: 295 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 1 units
    Since: Thu 1970-01-01 01:00:05 BST; 54 years 9 months ago
  systemd: 252.17-1~deb12u1+rpi1
   CGroup: /
           ├─init.scope
           │ └─1 /sbin/init
           ├─system.slice
           │ ├─ModemManager.service
           │ │ └─566 /usr/sbin/ModemManager
           │ ├─NetworkManager.service
           │ │ └─543 /usr/sbin/NetworkManager --no-daemon
           │ ├─avahi-daemon.service
           │ │ ├─470 "avahi-daemon: running [openHAB-pi.local]"
           │ │ └─493 "avahi-daemon: chroot helper"
           │ ├─bluetooth.service
           │ │ └─476 /usr/libexec/bluetooth/bluetoothd
           │ ├─cron.service
           │ │ └─477 /usr/sbin/cron -f
           │ ├─dbus.service

I hope someone can help me. 
Thanks
Hanimaniac

**Comment by pfink** [comment]
Hi, dependencies like the nuimo module are loaded with the command

pip3 install -r requirements.txt


Maybe you executed this command in the wrong path or it throwed an error message that you didn't see. You have to execute it where you cloned the requirements.txt from this repo.

**Comment by Hanimaniac** [comment]
Thank you for your feedback.

When I perform the comand pip3 install --upgrade -r nuimo-openhab-python/requirements.txt, I get this error:

pi@openHAB-pi:/etc/openhab2/nuimo-openhab-python $ sudo pip3 install --upgrade -r nuimo-openhab-python/requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by Hanimaniac** [comment]
We could solve the problem due to new installation method.

**Comment by Hanimaniac** [comment]
We could solve the problem due to new installation method.
